export const GET_MEETING_LIST_START = "GET_MEETING_LIST_START";
export const GET_MEETING_LIST_SUCCESS = "GET_MEETING_LIST_SUCCESS";
export const GET_MEETING_LIST_FAIL = "GET_MEETING_LIST_FAIL";

export const CREATE_MEETING_START = "CREATE_MEETING_START";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAIL = "CREATE_MEETING_FAIL";

export const UPDATE_MEETING_START = "UPDATE_MEETING_START";
export const UPDATE_MEETING_SUCCESS = "UPDATE_MEETING_SUCCESS";
export const UPDATE_MEETING_FAIL = "UPDATE_MEETING_FAIL";
