export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOG_OUT = "LOG_OUT";

export const GET_GRANTED_USER_INFO_START = "GET_GRANTED_USER_INFO_START";
export const GET_GRANTED_USER_INFO_SUCCESS = "GET_GRANTED_USER_INFO_SUCCESS";
export const GET_GRANTED_USER_INFO_FAIL = "GET_GRANTED_USER_INFO_FAIL";
