export const GET_MENU_API_ALL_START = "GET_MENU_API_ALL_START";
export const GET_MENU_API_ALL_SUCCESS = "GET_MENU_API_ALL_SUCCESS";
export const GET_MENU_API_ALL_FAIL = "GET_MENU_API_ALL_FAIL";

export const GET_GRANTED_GROUP_ALL_START = "GET_GRANTED_GROUP_ALL_START";
export const GET_GRANTED_GROUP_ALL_SUCCESS = "GET_GRANTED_GROUP_ALL_SUCCESS";
export const GET_GRANTED_GROUP_ALL_FAIL = "GET_GRANTED_GROUP_ALL_FAIL";

export const GET_GRANTED_USER_LIST_START = "GET_GRANTED_USER_LIST_START";
export const GET_GRANTED_USER_LIST_SUCCESS = "GET_GRANTED_USER_LIST_SUCCESS";
export const GET_GRANTED_USER_LIST_FAIL = "GET_GRANTED_USER_LIST_FAIL";

export const GET_ALL_FUNCTION_API_START = "GET_ALL_FUNCTION_API_START";
export const GET_ALL_FUNCTION_API_SUCCESS = "GET_ALL_FUNCTION_API_SUCCESS";
export const GET_ALL_FUNCTION_API_FAIL = "GET_ALL_FUNCTION_API_FAIL";

export const GET_ALL_ORGANIZATION_START = "GET_ALL_ORGANIZATION_START";
export const GET_ALL_ORGANIZATION_SUCCESS = "GET_ALL_ORGANIZATION_SUCCESS";
export const GET_ALL_ORGANIZATION_FAIL = "GET_ALL_ORGANIZATION_FAIL";

export const CREATE_MENU_API_START = "CREATE_MENU_API_START";
export const CREATE_MENU_API_SUCCESS = "CREATE_MENU_API_SUCCESS";
export const CREATE_MENU_API_FAIL = "CREATE_MENU_API_FAIL";

export const UPDATE_MENU_API_START = "UPDATE_MENU_API_START";
export const UPDATE_MENU_API_SUCCESS = "UPDATE_MENU_API_SUCCESS";
export const UPDATE_MENU_API_FAIL = "UPDATE_MENU_API_FAIL";

export const CREATE_FUNCTION_GROUP_START = "CREATE_FUNCTION_GROUP_START";
export const CREATE_FUNCTION_GROUP_SUCCESS = "CREATE_FUNCTION_GROUP_SUCCESS";
export const CREATE_FUNCTION_GROUP_FAIL = "CREATE_FUNCTION_GROUP_FAIL";

export const GRANT_FUNCTIONS_TO_GROUP_START = "GRANT_FUNCTIONS_TO_GROUP_START";
export const GRANT_FUNCTIONS_TO_GROUP_SUCCESS = "GRANT_FUNCTIONS_TO_GROUP_SUCCESS";
export const GRANT_FUNCTIONS_TO_GROUP_FAIL = "GRANT_FUNCTIONS_TO_GROUP_FAIL";

export const CREATE_ORGANIZATION_START = "CREATE_ORGANIZATION_START";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAIL = "CREATE_ORGANIZATION_FAIL";

export const UPDATE_ORGANIZATION_START = "UPDATE_ORGANIZATION_START";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAIL = "UPDATE_ORGANIZATION_FAIL";
