export const GET_MENU_API_ALL_START = "GET_MENU_API_ALL_START";
export const GET_MENU_API_ALL_SUCCESS = "GET_MENU_API_ALL_SUCCESS";
export const GET_MENU_API_ALL_FAIL = "GET_MENU_API_ALL_FAIL";

export const GET_GRANTED_USER_LIST_START = "GET_GRANTED_USER_LIST_START";
export const GET_GRANTED_USER_LIST_SUCCESS = "GET_GRANTED_USER_LIST_SUCCESS";
export const GET_GRANTED_USER_LIST_FAIL = "GET_GRANTED_USER_LIST_FAIL";

export const GET_GROUP_USER_LIST_START = "GET_GROUP_USER_LIST_START";
export const GET_GROUP_USER_LIST_SUCCESS = "GET_GROUP_USER_LIST_SUCCESS";
export const GET_GROUP_USER_LIST_FAIL = "GET_GROUP_USER_LIST_FAIL";
