export const GET_MENU_API_ALL_START = "GET_MENU_API_ALL_START";
export const GET_MENU_API_ALL_SUCCESS = "GET_MENU_API_ALL_SUCCESS";
export const GET_MENU_API_ALL_FAIL = "GET_MENU_API_ALL_FAIL";

export const GET_GRANTED_USER_LIST_START = "GET_GRANTED_USER_LIST_START";
export const GET_GRANTED_USER_LIST_SUCCESS = "GET_GRANTED_USER_LIST_SUCCESS";
export const GET_GRANTED_USER_LIST_FAIL = "GET_GRANTED_USER_LIST_FAIL";

export const GET_GROUP_USER_LIST_START = "GET_GROUP_USER_LIST_START";
export const GET_GROUP_USER_LIST_SUCCESS = "GET_GROUP_USER_LIST_SUCCESS";
export const GET_GROUP_USER_LIST_FAIL = "GET_GROUP_USER_LIST_FAIL";

export const CREATE_MENU_API_START = "CREATE_MENU_API_START";
export const CREATE_MENU_API_SUCCESS = "CREATE_MENU_API_SUCCESS";
export const CREATE_MENU_API_FAIL = "CREATE_MENU_API_FAIL";

export const UPDATE_MENU_API_START = "UPDATE_MENU_API_START";
export const UPDATE_MENU_API_SUCCESS = "UPDATE_MENU_API_SUCCESS";
export const UPDATE_MENU_API_FAIL = "UPDATE_MENU_API_FAIL";
