POST http://localhost:9232/leader-direct/api/get-direct-exe-by-dos
Content-Type: application/json
Authorization: eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNTM5OTM1NDg2OCwiZXhwIjoxNjU2OTM1MzU0ODY4fQ==.WXl0QU5DUmZNNTFHeVA3R3dzYklRcUdjOXVEclpLbGJsQ1pGRGxmd3dlNnZkd1dBZHNqVkcxY2VsOTI0bkhhcWUzNmprcHFLa2M3KzZlaFV3TFF5UHc9PQ==

{
    "uuidArr": ["3ed9faad-2024-49f1-8a5e-ca447510db3e"]
}

###
POST http://localhost:9232/leader-direct/api/get-filter-meeting
Content-Type: application/json
Authorization: eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNTM5OTM1NDg2OCwiZXhwIjoxNjU2OTM1MzU0ODY4fQ==.WXl0QU5DUmZNNTFHeVA3R3dzYklRcUdjOXVEclpLbGJsQ1pGRGxmd3dlNnZkd1dBZHNqVkcxY2VsOTI0bkhhcWUzNmprcHFLa2M3KzZlaFV3TFF5UHc9PQ==

{
    "created_time": {"from": 1626189072000, "to": 1626354152767},
    "category": [42]
}

###
POST http://localhost:9232/leader-direct/api/get-filter-direct
Content-Type: application/json
Authorization: eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNTM5OTM1NDg2OCwiZXhwIjoxNjU2OTM1MzU0ODY4fQ==.WXl0QU5DUmZNNTFHeVA3R3dzYklRcUdjOXVEclpLbGJsQ1pGRGxmd3dlNnZkd1dBZHNqVkcxY2VsOTI0bkhhcWUzNmprcHFLa2M3KzZlaFV3TFF5UHc9PQ==

{
    "created_time": {"from": 1626189072000, "to": 1626354152767},
    "category": [35],
    "meeting_id": [1]
}

###
POST http://localhost:9232/leader-direct/api/get-filter-direct-org
Content-Type: application/json
Authorization: eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNTM5OTM1NDg2OCwiZXhwIjoxNjU2OTM1MzU0ODY4fQ==.WXl0QU5DUmZNNTFHeVA3R3dzYklRcUdjOXVEclpLbGJsQ1pGRGxmd3dlNnZkd1dBZHNqVkcxY2VsOTI0bkhhcWUzNmprcHFLa2M3KzZlaFV3TFF5UHc9PQ==

{
    "created_time": {"from": 1626189072000, "to": 1626354152767},
    "exec_status": [11,12],
    "organization_id": [5],
    "organization_role": [21,22]
}
    
    