@baseHost = localhost
@basePort = 9232
# @baseHost = 10.16.150.69
@authToken = eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNTM5OTM1NDg2OCwiZXhwIjoxNjU2OTM1MzU0ODY4fQ==.WXl0QU5DUmZNNTFHeVA3R3dzYklRcUdjOXVEclpLbGJsQ1pGRGxmd3dlNnZkd1dBZHNqVkcxY2VsOTI0bkhhcWUzNmprcHFLa2M3KzZlaFV3TFF5UHc9PQ==


###
POST http://{{baseHost}}:{{basePort}}/leader-direct/api/get-filter-direct
Content-Type: application/json
Authorization: {{authToken}}

{
    "created_time": {"from": 1626189072000, "to": 1636354152767},
    "category": [35],
    "meeting_id": [1]
}

###
POST http://{{baseHost}}:{{basePort}}/leader-direct/api/create-direct
User-Agent: rest-client
Content-Type: application/json
Authorization: {{authToken}}

{
    "category": 35,
    "meeting_id": 1,
    "description": "Test Nhập Chỉ Đạo 2",
    "leader": 71,
    "executors": "[7,8,9]",
    "assessors": "[3]"
}

###
POST http://{{baseHost}}:{{basePort}}/leader-direct/api/update-direct
User-Agent: rest-client
Content-Type: application/json
Authorization: {{authToken}}

{
    "meeting_id": 1,
    "uuid": "aee38bd4-59f1-4d03-85ef-1b8f9722530a",
    "category": 35,
    "description": "Test Nhập Chỉ Đạo - EDIT",
    "leader": 71,
    "executors": "[6]",
    "assessors": "[2,4]"
}

###
POST http://{{baseHost}}:{{basePort}}/leader-direct/api/update-direct-criteria
User-Agent: rest-client
Content-Type: application/json
Authorization: {{authToken}}

{
    "direct_uuid": "94676e20-15fe-489f-bb1a-53209c76eb32",
    "assess_criteria": [
        {
            "organization": {"id": 3, "name": "P.TH"},
            "created_time": "01/08/2021",
            "due_date": "10/08/2021",
            "description": "Test nhập criteria cho direct"
        }
    ]
}
