@baseHost = localhost
@basePort = 9232
# @baseHost = 10.16.150.69
@authToken = eyJ1c2VybmFtZSI6ImhpZXUucXVhbmciLCJkZXZpY2VfaWQiOm51bGwsImlhdCI6MTYyNjYyMjM3MDU4OSwiZXhwIjoxNjU4MTU4MzcwNTg5fQ==.WlVXNVF3VzA0VEtFTnNiNmt5ZFR3eld1RHNFNmRzb1QzM1hDUE9Ob0RRVHNZcWg3c2MxZ0ZZWDhxc3BtWGlpNFg4cjByUXhSZWdveitBRjNYdk9DRWc9PQ==


POST http://{{baseHost}}:{{basePort}}/leader-direct/api/get-filter-direct-ass
Content-Type: application/json
Authorization: {{authToken}}

{
    "created_time": {"from": 1626189072000, "to": 1666354152767}
}

###
POST http://{{baseHost}}:{{basePort}}/leader-direct/api/update-direct-assessment-logs
Content-Type: application/json
Authorization: {{authToken}}

{
    "log_uuid": "dcecd58b-5c3b-4c97-830e-096de143f140",
    "description": "asdfasd edit 1",
    "direct_ass_uuid": "a049c6e0-4f24-4396-8a19-9c32ea6b6518",
    "direct_exe_uuid": "09ba8442-b300-485e-a953-ecf9d49a9f80",
    "direct_org_uuid": "c1d0dd21-7df5-436e-9413-4529b5604dbe",
    "direct_uuid": "94676e20-15fe-489f-bb1a-53209c76eb32",
    "organization_ass": 2,
    "organization_exe": 3
}
