export const WIPE_REPORT_EXCEL_DATA = "WIPE_REPORT_EXCEL_DATA";

export const GET_REPORT_DIRECT_AGG_EXCEL_START = "GET_REPORT_DIRECT_AGG_EXCEL_START";
export const GET_REPORT_DIRECT_AGG_EXCEL_SUCCESS = "GET_REPORT_DIRECT_AGG_EXCEL_SUCCESS";
export const GET_REPORT_DIRECT_AGG_EXCEL_FAIL = "GET_REPORT_DIRECT_AGG_EXCEL_FAIL";

export const GET_REPORT_DIRECT_DETAIL_EXCEL_START = "GET_REPORT_DIRECT_DETAIL_EXCEL_START";
export const GET_REPORT_DIRECT_DETAIL_EXCEL_SUCCESS = "GET_REPORT_DIRECT_DETAIL_EXCEL_SUCCESS";
export const GET_REPORT_DIRECT_DETAIL_EXCEL_FAIL = "GET_REPORT_DIRECT_DETAIL_EXCEL_FAIL";
