export const GET_DIRECT_ORG_ALL_START = "GET_DIRECT_ORG_ALL_START";
export const GET_DIRECT_ORG_ALL_SUCCESS = "GET_DIRECT_ORG_ALL_SUCCESS";
export const GET_DIRECT_ORG_ALL_FAIL = "GET_DIRECT_ORG_ALL_FAIL";

export const GET_DIRECT_ORG_BY_ORG_START = "GET_DIRECT_ORG_BY_ORG_START";
export const GET_DIRECT_ORG_BY_ORG_SUCCESS = "GET_DIRECT_ORG_BY_ORG_SUCCESS";
export const GET_DIRECT_ORG_BY_ORG_FAIL = "GET_DIRECT_ORG_BY_ORG_FAIL";

export const UPDATE_DIRECT_ORG_START = "UPDATE_DIRECT_ORG_START";
export const UPDATE_DIRECT_ORG_SUCCESS = "UPDATE_DIRECT_ORG_SUCCESS";
export const UPDATE_DIRECT_ORG_FAIL = "UPDATE_DIRECT_ORG_FAIL";
